CREATE TABLE tb_company_overview (
    symbol VARCHAR(10) PRIMARY KEY,
    nm_asset_type VARCHAR(50),
    nm_name VARCHAR(255),
    nm_description TEXT,
    nm_cik VARCHAR(20),
    nm_exchange VARCHAR(20),
    nm_currency CHAR(3),
    nm_country VARCHAR(100),
    nm_sector VARCHAR(100),
    nm_industry VARCHAR(100),
    nm_address TEXT,
    nm_official_site VARCHAR(255),
    nm_fiscal_year_end VARCHAR(20),
    dt_latest_quarter DATE,
    vl_market_capitalization NUMERIC(20, 0),
    vl_ebitda NUMERIC(20, 0),
    vl_pe_ratio NUMERIC(10, 2),
    vl_peg_ratio NUMERIC(10, 3),
    vl_book_value NUMERIC(10, 2),
    vl_dividend_per_share NUMERIC(10, 2),
    vl_dividend_yield NUMERIC(10, 4),
    vl_eps NUMERIC(10, 2),
    vl_revenue_per_share_ttm NUMERIC(10, 2),
    vl_profit_margin NUMERIC(10, 3),
    vl_operating_margin_ttm NUMERIC(10, 3),
    vl_return_on_assets_ttm NUMERIC(10, 4),
    vl_return_on_equity_ttm NUMERIC(10, 3),
    vl_revenue_ttm NUMERIC(20, 0),
    vl_gross_profit_ttm NUMERIC(20, 0),
    vl_diluted_eps_ttm NUMERIC(10, 2),
    vl_quarterly_earnings_growth_yoy NUMERIC(10, 3),
    vl_quarterly_revenue_growth_yoy NUMERIC(10, 2),
    vl_analyst_target_price NUMERIC(10, 2),
    qt_analyst_rating_strong_buy INTEGER,
    qt_analyst_rating_buy INTEGER,
    qt_analyst_rating_hold INTEGER,
    qt_analyst_rating_sell INTEGER,
    qt_analyst_rating_strong_sell INTEGER,
    vl_trailing_pe NUMERIC(10, 2),
    vl_forward_pe NUMERIC(10, 2),
    vl_price_to_sales_ratio_ttm NUMERIC(10, 2),
    vl_price_to_book_ratio NUMERIC(10, 2),
    vl_ev_to_revenue NUMERIC(10, 3),
    vl_ev_to_ebitda NUMERIC(10, 2),
    vl_beta NUMERIC(10, 3),
    vl_52week_high NUMERIC(10, 2),
    vl_52week_low NUMERIC(10, 2),
    vl_50day_moving_average NUMERIC(10, 2),
    vl_200day_moving_average NUMERIC(10, 2),
    qt_shares_outstanding NUMERIC(20, 0),
    dt_dividend_date DATE,
    dt_ex_dividend_date DATE
);